# Site settings
title: Emanuele Di Marco
description: 'Researcher at Istituto Nazionale di Fisica Nucleare, Sezione di Roma 1'
url: 'http://www.roma1.infn.it'
baseurl: '/people/dimarcoe'
google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Emanuele Di Marco'
  email: emanuele.dimarco@roma1.infn.it
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
  github_username:  emanueledimarco
#  linkedin_username:  joshgerdes
  phone: 00390649914388
  googlemaps: 'https://www.google.com/maps/search/?api=1&query=piazzale+aldo+moro+2+roma'

collections:
  research:
    defaults:
      layout: post
#   output: true
    permalink: /research/:path/
  teaching:
    defaults:
      layout: post
#   output: true
    permalink: /teaching/:path/


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-email-protect']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

